### ISSUE TITLE
README: Be specific about supported browsers

### ISSUE THREAD

**Issue by mathiasbynens** [olov/stringmap#1]
E.g. since `delete` is [a keyword in ES3](http://mothereff.in/js-properties#delete), this library won’t work in browsers with an ES3 engine.

**Comment by olov** [comment]
Thanks for opening the issue Mathias!

The library does work in ES3 engines, but the user need to call the method like so: `sm['delete']("kramer")`. And yeah, that is awkward. I realize now that `example.js` doesn't show this (but `stringmap.js` itself does).

I use the `delete` name for the method to be consistent with ES6 Map. I will push out a new release where the default name is `remove`, but `delete` is available as an alias. Closing the issue once that is done.

**Comment by olov** [comment]
For clarity: The library is expected to work everywhere so if you can find a corner case bug in some particular browser, please file an issue!
